---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: pong
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/Frnn4268/flux-experiments.git
